osx_image: xcode8
language: objective-c

before_install:
  - brew update
  - brew install tailor

script:
- xcodebuild analyze -workspace HanabiCollectionViewLayout.xcworkspace -scheme HanabiCollectionViewLayout -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s Plus' | xcpretty -c
- pod lib lint HanabiCollectionViewLayout.podspec --quick
