osx_image: xcode7.2
language: objective-c

script:
- xcodebuild analyze -workspace HanabiCollectionViewLayout.xcworkspace -scheme HanabiCollectionViewLayout -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s Plus' | xcpretty -c
- pod lib lint HanabiCollectionViewLayout.podspec --quick
