language: objective-c
os: osx
osx_image: xcode7

install:
- gem install cocoapods xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail && xcodebuild -project HanabiExample/HanabiExample.xcodeproj -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint HanabiCollectionViewLayout.podspec --quick
